language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - j.bernal@upm.es
script:
# Unit Test & Integration Test
- mvn verify --settings settings.xml
# Functional Testing
- if [ $TRAVIS_BRANCH == "develop" ]; then
      mvn verify -Ppreproduction --settings settings.xml; 
    else 
      echo "Skip Functional Testing!"; 
    fi